version: '3.4'
services:
  stress:
    image: progrium/stress
    command: --cpu 2 --io 4 --vm 1 --timeout 20s
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: '0.15'
          memory: 300M

#  pgbench_init:
#  image: postgres:10.1
#    command: pgbench -i
#    deploy:
#      restart_policy:
#        condition: never
#      resources:
#        limits:
#          cpus: '0.15'
#          memory: 300M

#  pgbench:
#    image: postgres:10.1
#      command: pgbench -i
#      deploy:
#        replicas: 3
#        restart_policy:
#          condition: always
#        resources:
#          limits:
#            cpus: '0.15'
#            memory: 300M
#
#  postgres:
#    image: postgres:10.1
#    deploy:
#      restart_policy:
#        condition: always
#    environment:
#      POSTGRES_USER: pgbench
#      POSTGRES_PASSWORD: mysecretpassword



