version: "3"
services:

  locust-master:
    image: nukapi/infrastructurepunisher
    ports:
      - "8089:8089"
    command: "locust -f locust.py --host=https://www.example.com"

  locust-worker:
    image: nukapi/infrastructurepunisher
    command: "locust -f locust.py --host=https://www.example.com --master-host=locust-master"
    deploy:
      replicas: 20